"""found goods flag on count items

Revision ID: 5386efc05194
Revises: bdb616594630
Create Date: 2026-10-05 20:39:35.354462

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5386efc05194"
down_revision: str | Sequence[str] | None = "bdb616594630"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "count_items",
        sa.Column("najdeno", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_count_items_najdeno_not_in_book"),
        "count_items",
        "NOT najdeno OR knjizena_kolicina = 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_count_items_najdeno_not_in_book"), "count_items", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("count_items", "najdeno")
    # ### end Alembic commands ###
