"""initial schema

Revision ID: bdb616594630
Revises:
Create Date: 2026-10-05 19:18:19.040384

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdb616594630"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sifra", sa.String(length=40), nullable=False),
        sa.Column("opis", sa.String(length=200), nullable=False),
        sa.Column("merska_enota", sa.String(length=40), nullable=False),
        sa.Column("cena_na_enoto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.CheckConstraint("cena_na_enoto >= 0", name=op.f("ck_materials_cena_not_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("sifra", name=op.f("uq_materials_sifra")),
    )
    op.create_table(
        "stock_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "uvozeno_ob",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("izvorna_datoteka", sa.String(length=255), nullable=False),
        sa.Column("stevilo_vrstic", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_snapshots")),
    )
    op.create_table(
        "count_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("regal", sa.String(length=40), nullable=False),
        sa.Column("zaporedna_st", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("odprt", "v_stetju", "ponovno_stetje", "zakljucen", name="document_status"),
            nullable=False,
        ),
        sa.Column(
            "ustvarjen_ob",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("zakljucen_ob", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["stock_snapshots.id"],
            name=op.f("fk_count_documents_snapshot_id_stock_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_count_documents")),
        sa.UniqueConstraint("snapshot_id", "regal", name="uq_count_documents_rack"),
        sa.UniqueConstraint("snapshot_id", "zaporedna_st", name="uq_count_documents_number"),
    )
    op.create_table(
        "stock_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("lokacija", sa.String(length=40), nullable=False),
        sa.Column("regal", sa.String(length=40), nullable=False),
        sa.Column("nivo", sa.Integer(), nullable=False),
        sa.Column("polozaj", sa.Integer(), nullable=False),
        sa.Column("sarza", sa.String(length=40), nullable=True),
        sa.Column("kolicina", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("cena_na_enoto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vrstica", sa.Integer(), nullable=False),
        sa.CheckConstraint("cena_na_enoto >= 0", name=op.f("ck_stock_items_cena_not_negative")),
        sa.CheckConstraint("kolicina >= 0", name=op.f("ck_stock_items_kolicina_not_negative")),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name=op.f("fk_stock_items_material_id_materials")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["stock_snapshots.id"],
            name=op.f("fk_stock_items_snapshot_id_stock_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_items")),
        sa.UniqueConstraint(
            "snapshot_id",
            "material_id",
            "regal",
            "nivo",
            "polozaj",
            "sarza",
            name="uq_stock_items_position",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "count_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("lokacija", sa.String(length=40), nullable=False),
        sa.Column("nivo", sa.Integer(), nullable=False),
        sa.Column("polozaj", sa.Integer(), nullable=False),
        sa.Column("sarza", sa.String(length=40), nullable=True),
        sa.Column("knjizena_kolicina", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("cena_na_enoto", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("presteta_kolicina", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("stevec", sa.String(length=100), nullable=True),
        sa.Column("presteto_ob", sa.DateTime(timezone=True), nullable=True),
        sa.Column("krog", sa.Integer(), nullable=False),
        sa.CheckConstraint("cena_na_enoto >= 0", name=op.f("ck_count_items_cena_not_negative")),
        sa.CheckConstraint(
            "knjizena_kolicina >= 0", name=op.f("ck_count_items_knjizena_not_negative")
        ),
        sa.CheckConstraint("krog >= 1", name=op.f("ck_count_items_krog_positive")),
        sa.CheckConstraint(
            "presteta_kolicina >= 0", name=op.f("ck_count_items_presteta_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["count_documents.id"],
            name=op.f("fk_count_items_document_id_count_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name=op.f("fk_count_items_material_id_materials")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_count_items")),
        sa.UniqueConstraint(
            "document_id",
            "material_id",
            "nivo",
            "polozaj",
            "sarza",
            "krog",
            name="uq_count_items_position_round",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_count_items_document_order",
        "count_items",
        ["document_id", "nivo", "polozaj"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_count_items_document_order", table_name="count_items")
    op.drop_table("count_items")
    op.drop_table("stock_items")
    op.drop_table("count_documents")
    op.drop_table("stock_snapshots")
    op.drop_table("materials")
    # ### end Alembic commands ###
    sa.Enum(name="document_status").drop(op.get_bind(), checkfirst=True)
